// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/models/shared"
	"net/http"
)

type CreateStagesFileRequest struct {
	// Path in Stages
	Path string `pathParam:"style=simple,explode=false,name=path"`
	// ID of the Stages-enabled workspace group
	WorkspaceGroupID        string                          `pathParam:"style=simple,explode=false,name=workspaceGroupID"`
	CreateStagesFileRequest *shared.CreateStagesFileRequest `request:"mediaType=multipart/form-data"`
	// If set to `true`, forces creation of an empty file
	IsFile *bool `queryParam:"style=form,explode=true,name=isFile"`
}

func (o *CreateStagesFileRequest) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *CreateStagesFileRequest) GetWorkspaceGroupID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceGroupID
}

func (o *CreateStagesFileRequest) GetCreateStagesFileRequest() *shared.CreateStagesFileRequest {
	if o == nil {
		return nil
	}
	return o.CreateStagesFileRequest
}

func (o *CreateStagesFileRequest) GetIsFile() *bool {
	if o == nil {
		return nil
	}
	return o.IsFile
}

type CreateStagesFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	CreateStagesFile *shared.CreateStagesFile
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateStagesFileResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateStagesFileResponse) GetCreateStagesFile() *shared.CreateStagesFile {
	if o == nil {
		return nil
	}
	return o.CreateStagesFile
}

func (o *CreateStagesFileResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateStagesFileResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
