// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/models/shared"
	"net/http"
)

type CreateWorkspaceGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	CreateWorkspaceGroup *shared.CreateWorkspaceGroup
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateWorkspaceGroupResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateWorkspaceGroupResponse) GetCreateWorkspaceGroup() *shared.CreateWorkspaceGroup {
	if o == nil {
		return nil
	}
	return o.CreateWorkspaceGroup
}

func (o *CreateWorkspaceGroupResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateWorkspaceGroupResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
