// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/models/shared"
	"net/http"
)

type DeletePrivateConnectionRequest struct {
	// ID of the private connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connectionID"`
}

func (o *DeletePrivateConnectionRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

type DeletePrivateConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	DeletePrivateConnection *shared.DeletePrivateConnection
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeletePrivateConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeletePrivateConnectionResponse) GetDeletePrivateConnection() *shared.DeletePrivateConnection {
	if o == nil {
		return nil
	}
	return o.DeletePrivateConnection
}

func (o *DeletePrivateConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeletePrivateConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
