// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/models/shared"
	"net/http"
)

type GetOutboundWorkspaceRequest struct {
	// ID of the workspace
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

func (o *GetOutboundWorkspaceRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

type GetOutboundWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	PrivateConnectionOutboundAllowLists []shared.PrivateConnectionOutboundAllowList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetOutboundWorkspaceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetOutboundWorkspaceResponse) GetPrivateConnectionOutboundAllowLists() []shared.PrivateConnectionOutboundAllowList {
	if o == nil {
		return nil
	}
	return o.PrivateConnectionOutboundAllowLists
}

func (o *GetOutboundWorkspaceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetOutboundWorkspaceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
