// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/models/shared"
	"net/http"
)

type GetRecoveryBackupWorkspaceRequest struct {
	// ID of the workspace
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
	// Comma-separated values list that correspond to the filtered fields for returned entities
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
}

func (o *GetRecoveryBackupWorkspaceRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *GetRecoveryBackupWorkspaceRequest) GetFields() *string {
	if o == nil {
		return nil
	}
	return o.Fields
}

type GetRecoveryBackupWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	Regions []shared.Region
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetRecoveryBackupWorkspaceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRecoveryBackupWorkspaceResponse) GetRegions() []shared.Region {
	if o == nil {
		return nil
	}
	return o.Regions
}

func (o *GetRecoveryBackupWorkspaceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRecoveryBackupWorkspaceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
