// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/models/shared"
	"net/http"
)

type ListWorkspaceRequest struct {
	// Comma-separated values list that correspond to the filtered fields for returned entities
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// To include any terminated workspaces, set to `true`
	IncludeTerminated *bool `queryParam:"style=form,explode=true,name=includeTerminated"`
	// ID of the workspace group
	WorkspaceGroupID string `queryParam:"style=form,explode=true,name=workspaceGroupID"`
}

func (o *ListWorkspaceRequest) GetFields() *string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *ListWorkspaceRequest) GetIncludeTerminated() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeTerminated
}

func (o *ListWorkspaceRequest) GetWorkspaceGroupID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceGroupID
}

type ListWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Workspaces []shared.Workspace
}

func (o *ListWorkspaceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListWorkspaceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListWorkspaceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListWorkspaceResponse) GetWorkspaces() []shared.Workspace {
	if o == nil {
		return nil
	}
	return o.Workspaces
}
