// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/models/shared"
	"net/http"
)

type UpdateWorkspaceRequest struct {
	// Here's a sample of JSON data sent to the API in the request body.
	WorkspaceUpdate shared.WorkspaceUpdate `request:"mediaType=application/json"`
	// ID of the workspace
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

func (o *UpdateWorkspaceRequest) GetWorkspaceUpdate() shared.WorkspaceUpdate {
	if o == nil {
		return shared.WorkspaceUpdate{}
	}
	return o.WorkspaceUpdate
}

func (o *UpdateWorkspaceRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

type UpdateWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	CreateWorkspace *shared.CreateWorkspace
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateWorkspaceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateWorkspaceResponse) GetCreateWorkspace() *shared.CreateWorkspace {
	if o == nil {
		return nil
	}
	return o.CreateWorkspace
}

func (o *UpdateWorkspaceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateWorkspaceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
