// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/models/shared"
	"net/http"
)

type UpdateWorkspaceGroupsRequest struct {
	// Here's a sample of JSON data sent to the API in the request body.
	WorkspaceGroupUpdate shared.WorkspaceGroupUpdate `request:"mediaType=application/json"`
	// ID of the workspace group
	WorkspaceGroupID string `pathParam:"style=simple,explode=false,name=workspaceGroupID"`
}

func (o *UpdateWorkspaceGroupsRequest) GetWorkspaceGroupUpdate() shared.WorkspaceGroupUpdate {
	if o == nil {
		return shared.WorkspaceGroupUpdate{}
	}
	return o.WorkspaceGroupUpdate
}

func (o *UpdateWorkspaceGroupsRequest) GetWorkspaceGroupID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceGroupID
}

type UpdateWorkspaceGroupsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	UpdateWorkspaceGroups *shared.UpdateWorkspaceGroups
}

func (o *UpdateWorkspaceGroupsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateWorkspaceGroupsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateWorkspaceGroupsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateWorkspaceGroupsResponse) GetUpdateWorkspaceGroups() *shared.UpdateWorkspaceGroups {
	if o == nil {
		return nil
	}
	return o.UpdateWorkspaceGroups
}
