// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BillingUsageUsage struct {
	EndTime      *string `json:"endTime,omitempty"`
	OwnerID      *string `json:"ownerId,omitempty"`
	ResourceID   *string `json:"resourceId,omitempty"`
	ResourceName *string `json:"resourceName,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
	StartTime    *string `json:"startTime,omitempty"`
	Value        *string `json:"value,omitempty"`
}

func (o *BillingUsageUsage) GetEndTime() *string {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *BillingUsageUsage) GetOwnerID() *string {
	if o == nil {
		return nil
	}
	return o.OwnerID
}

func (o *BillingUsageUsage) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}

func (o *BillingUsageUsage) GetResourceName() *string {
	if o == nil {
		return nil
	}
	return o.ResourceName
}

func (o *BillingUsageUsage) GetResourceType() *string {
	if o == nil {
		return nil
	}
	return o.ResourceType
}

func (o *BillingUsageUsage) GetStartTime() *string {
	if o == nil {
		return nil
	}
	return o.StartTime
}

func (o *BillingUsageUsage) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

// BillingUsage - Represents a billing usage entity
type BillingUsage struct {
	// What the unit indicates
	Description *string `json:"description,omitempty"`
	// The metric name
	Metric *string             `json:"metric,omitempty"`
	Usage  []BillingUsageUsage `json:"usage,omitempty"`
}

func (o *BillingUsage) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *BillingUsage) GetMetric() *string {
	if o == nil {
		return nil
	}
	return o.Metric
}

func (o *BillingUsage) GetUsage() []BillingUsageUsage {
	if o == nil {
		return nil
	}
	return o.Usage
}
