// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"io"
)

type CreateStagesFileRequest1 struct {
	// File to upload
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	File io.ReadCloser `json:"file,omitempty"`
}

func (o *CreateStagesFileRequest1) GetFile() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.File
}
