// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateWorkspace struct {
	WorkspaceID string `json:"workspaceID"`
}

func (o *CreateWorkspace) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
