// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateStagesFileRequestFile struct {
	Content []byte `multipartForm:"content"`
	File    string `multipartForm:"name=file"`
}

func (o *CreateStagesFileRequestFile) GetContent() []byte {
	if o == nil {
		return []byte{}
	}
	return o.Content
}

func (o *CreateStagesFileRequestFile) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

type CreateStagesFileRequest struct {
	// File to upload
	File *CreateStagesFileRequestFile `multipartForm:"file"`
}

func (o *CreateStagesFileRequest) GetFile() *CreateStagesFileRequestFile {
	if o == nil {
		return nil
	}
	return o.File
}
