// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateStagesFile struct {
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

func (o *CreateStagesFile) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateStagesFile) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}
