// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateWorkspaceGroup struct {
	AdminPassword    *string `json:"adminPassword,omitempty"`
	WorkspaceGroupID string  `json:"workspaceGroupID"`
}

func (o *CreateWorkspaceGroup) GetAdminPassword() *string {
	if o == nil {
		return nil
	}
	return o.AdminPassword
}

func (o *CreateWorkspaceGroup) GetWorkspaceGroupID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceGroupID
}
