// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeleteStagesFile struct {
	// sample_file.txt
	Name *string `json:"name,omitempty"`
	// parent_folder/sample_file.txt
	Path *string `json:"path,omitempty"`
}

func (o *DeleteStagesFile) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *DeleteStagesFile) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}
