// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Organization - Represents information related to an organization
type Organization struct {
	// The list of allowed IP addresses which can access the Management API
	FirewallRanges []string `json:"firewallRanges,omitempty"`
	// Name of the organization
	Name *string `json:"name,omitempty"`
	// ID of the organization
	OrgID string `json:"orgID"`
}

func (o *Organization) GetFirewallRanges() []string {
	if o == nil {
		return nil
	}
	return o.FirewallRanges
}

func (o *Organization) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Organization) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}
