// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy-sdks/singlestore-sample-sdk/pkg/utils"
)

type StagesObjectMetadataContentType string

const (
	StagesObjectMetadataContentTypeStr                         StagesObjectMetadataContentType = "str"
	StagesObjectMetadataContentTypeArrayOfStagesObjectMetadata StagesObjectMetadataContentType = "arrayOfStagesObjectMetadata"
)

type StagesObjectMetadataContent struct {
	Str                         *string
	ArrayOfStagesObjectMetadata []StagesObjectMetadata

	Type StagesObjectMetadataContentType
}

func CreateStagesObjectMetadataContentStr(str string) StagesObjectMetadataContent {
	typ := StagesObjectMetadataContentTypeStr

	return StagesObjectMetadataContent{
		Str:  &str,
		Type: typ,
	}
}

func CreateStagesObjectMetadataContentArrayOfStagesObjectMetadata(arrayOfStagesObjectMetadata []StagesObjectMetadata) StagesObjectMetadataContent {
	typ := StagesObjectMetadataContentTypeArrayOfStagesObjectMetadata

	return StagesObjectMetadataContent{
		ArrayOfStagesObjectMetadata: arrayOfStagesObjectMetadata,
		Type:                        typ,
	}
}

func (u *StagesObjectMetadataContent) UnmarshalJSON(data []byte) error {

	str := ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = StagesObjectMetadataContentTypeStr
		return nil
	}

	arrayOfStagesObjectMetadata := []StagesObjectMetadata{}
	if err := utils.UnmarshalJSON(data, &arrayOfStagesObjectMetadata, "", true, true); err == nil {
		u.ArrayOfStagesObjectMetadata = arrayOfStagesObjectMetadata
		u.Type = StagesObjectMetadataContentTypeArrayOfStagesObjectMetadata
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u StagesObjectMetadataContent) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStagesObjectMetadata != nil {
		return utils.MarshalJSON(u.ArrayOfStagesObjectMetadata, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// StagesObjectMetadataFormat - Format of the response
type StagesObjectMetadataFormat string

const (
	StagesObjectMetadataFormatJSON                   StagesObjectMetadataFormat = "json"
	StagesObjectMetadataFormatLessThanNilGreaterThan StagesObjectMetadataFormat = "<nil>"
)

func (e StagesObjectMetadataFormat) ToPointer() *StagesObjectMetadataFormat {
	return &e
}

func (e *StagesObjectMetadataFormat) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "json":
		fallthrough
	case "<nil>":
		*e = StagesObjectMetadataFormat(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StagesObjectMetadataFormat: %v", v)
	}
}

// StagesObjectMetadataType - Object type
type StagesObjectMetadataType string

const (
	StagesObjectMetadataTypeUnknown                StagesObjectMetadataType = ""
	StagesObjectMetadataTypeJSON                   StagesObjectMetadataType = "json"
	StagesObjectMetadataTypeDirectory              StagesObjectMetadataType = "directory"
	StagesObjectMetadataTypeLessThanNilGreaterThan StagesObjectMetadataType = "<nil>"
)

func (e StagesObjectMetadataType) ToPointer() *StagesObjectMetadataType {
	return &e
}

func (e *StagesObjectMetadataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "json":
		fallthrough
	case "directory":
		fallthrough
	case "<nil>":
		*e = StagesObjectMetadataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StagesObjectMetadataType: %v", v)
	}
}

// StagesObjectMetadata - Represents the metadata corresponding to an object in Stages
type StagesObjectMetadata struct {
	Content *StagesObjectMetadataContent `json:"content,omitempty"`
	Created *string                      `json:"created,omitempty"`
	// Format of the response
	Format       *StagesObjectMetadataFormat `json:"format,omitempty"`
	LastModified *string                     `json:"last_modified,omitempty"`
	Mimetype     *string                     `json:"mimetype,omitempty"`
	// Name of the Stages object
	Name *string `json:"name,omitempty"`
	// Path of the Stages object
	Path *string `json:"path,omitempty"`
	Size *int64  `json:"size,omitempty"`
	// Object type
	Type     *StagesObjectMetadataType `json:"type,omitempty"`
	Writable *bool                     `json:"writable,omitempty"`
}

func (o *StagesObjectMetadata) GetContent() *StagesObjectMetadataContent {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *StagesObjectMetadata) GetCreated() *string {
	if o == nil {
		return nil
	}
	return o.Created
}

func (o *StagesObjectMetadata) GetFormat() *StagesObjectMetadataFormat {
	if o == nil {
		return nil
	}
	return o.Format
}

func (o *StagesObjectMetadata) GetLastModified() *string {
	if o == nil {
		return nil
	}
	return o.LastModified
}

func (o *StagesObjectMetadata) GetMimetype() *string {
	if o == nil {
		return nil
	}
	return o.Mimetype
}

func (o *StagesObjectMetadata) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *StagesObjectMetadata) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *StagesObjectMetadata) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *StagesObjectMetadata) GetType() *StagesObjectMetadataType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *StagesObjectMetadata) GetWritable() *bool {
	if o == nil {
		return nil
	}
	return o.Writable
}
