// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UpdateWorkspaceGroups struct {
	WorkspaceGroupID string `json:"workspaceGroupID"`
}

func (o *UpdateWorkspaceGroups) GetWorkspaceGroupID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceGroupID
}
