// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkspaceUpdate - Represents the information specified while updating a workspace
type WorkspaceUpdate struct {
	// Size of the workspace (in workspace size notation), such as "S-1". The default value is "S-00".
	//
	Size *string `json:"size,omitempty"`
}

func (o *WorkspaceUpdate) GetSize() *string {
	if o == nil {
		return nil
	}
	return o.Size
}
