// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// WorkspaceGroupState - State of the workspace group
type WorkspaceGroupState string

const (
	WorkspaceGroupStateActive     WorkspaceGroupState = "ACTIVE"
	WorkspaceGroupStatePending    WorkspaceGroupState = "PENDING"
	WorkspaceGroupStateFailed     WorkspaceGroupState = "FAILED"
	WorkspaceGroupStateTerminated WorkspaceGroupState = "TERMINATED"
)

func (e WorkspaceGroupState) ToPointer() *WorkspaceGroupState {
	return &e
}

func (e *WorkspaceGroupState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACTIVE":
		fallthrough
	case "PENDING":
		fallthrough
	case "FAILED":
		fallthrough
	case "TERMINATED":
		*e = WorkspaceGroupState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WorkspaceGroupState: %v", v)
	}
}

// WorkspaceGroup - Represents information related to a workspace group
type WorkspaceGroup struct {
	// Whether or not all traffic is allowed to the workspace group
	AllowAllTraffic *bool `json:"allowAllTraffic,omitempty"`
	// The timestamp of when the workspace was created
	CreatedAt string `json:"createdAt"`
	// The timestamp of when the workspace group will expire. At expiration, the workspace group is terminated and all the data is lost.
	ExpiresAt *string `json:"expiresAt,omitempty"`
	// The list of allowed inbound IP addresses. An empty list indicates that no inbound requests are allowed.
	FirewallRanges []string `json:"firewallRanges,omitempty"`
	// Name of the workspace group
	Name string `json:"name"`
	// ID of the region
	RegionID string `json:"regionID"`
	// State of the workspace group
	State WorkspaceGroupState `json:"state"`
	// (If included in the output) The timestamp of when the workspace group was terminated
	TerminatedAt *string `json:"terminatedAt,omitempty"`
	// Represents information related to an update window
	UpdateWindow *UpdateWindow `json:"updateWindow,omitempty"`
	// ID of the workspace group
	WorkspaceGroupID string `json:"workspaceGroupID"`
}

func (o *WorkspaceGroup) GetAllowAllTraffic() *bool {
	if o == nil {
		return nil
	}
	return o.AllowAllTraffic
}

func (o *WorkspaceGroup) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *WorkspaceGroup) GetExpiresAt() *string {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *WorkspaceGroup) GetFirewallRanges() []string {
	if o == nil {
		return nil
	}
	return o.FirewallRanges
}

func (o *WorkspaceGroup) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *WorkspaceGroup) GetRegionID() string {
	if o == nil {
		return ""
	}
	return o.RegionID
}

func (o *WorkspaceGroup) GetState() WorkspaceGroupState {
	if o == nil {
		return WorkspaceGroupState("")
	}
	return o.State
}

func (o *WorkspaceGroup) GetTerminatedAt() *string {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}

func (o *WorkspaceGroup) GetUpdateWindow() *UpdateWindow {
	if o == nil {
		return nil
	}
	return o.UpdateWindow
}

func (o *WorkspaceGroup) GetWorkspaceGroupID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceGroupID
}
