// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Attachment - The type of attachment
type Attachment string

const (
	AttachmentReadwrite Attachment = "READWRITE"
	AttachmentReadonly  Attachment = "READONLY"
)

func (e Attachment) ToPointer() *Attachment {
	return &e
}

func (e *Attachment) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "READWRITE":
		fallthrough
	case "READONLY":
		*e = Attachment(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Attachment: %v", v)
	}
}

// ResumeAttachments - Represents information related to database attachments
type ResumeAttachments struct {
	// The type of attachment
	Attachment Attachment `json:"attachment"`
	// Name of the database
	Database string `json:"database"`
	// The error if the attachment was not successful
	Error *string `json:"error,omitempty"`
	// Whether the attachment was successful or not
	Success bool `json:"success"`
}

func (o *ResumeAttachments) GetAttachment() Attachment {
	if o == nil {
		return Attachment("")
	}
	return o.Attachment
}

func (o *ResumeAttachments) GetDatabase() string {
	if o == nil {
		return ""
	}
	return o.Database
}

func (o *ResumeAttachments) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ResumeAttachments) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

// State of the workspace
type State string

const (
	StateActive     State = "ACTIVE"
	StatePending    State = "PENDING"
	StateSuspended  State = "SUSPENDED"
	StateFailed     State = "FAILED"
	StateTerminated State = "TERMINATED"
)

func (e State) ToPointer() *State {
	return &e
}

func (e *State) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACTIVE":
		fallthrough
	case "PENDING":
		fallthrough
	case "SUSPENDED":
		fallthrough
	case "FAILED":
		fallthrough
	case "TERMINATED":
		*e = State(v)
		return nil
	default:
		return fmt.Errorf("invalid value for State: %v", v)
	}
}

// Workspace - Represents information related to a workspace
type Workspace struct {
	// The timestamp of when the workspace was created
	CreatedAt string `json:"createdAt"`
	// Endpoint to connect to the workspace
	Endpoint *string `json:"endpoint,omitempty"`
	// (If included in the output) The timestamp of when the workspace was last resumed
	LastResumedAt *string `json:"lastResumedAt,omitempty"`
	// Name of the workspace
	Name string `json:"name"`
	// (If included in the output) The result of database attachments after the workspace was resumed
	ResumeAttachments []ResumeAttachments `json:"resumeAttachments,omitempty"`
	// (If included in the output) The current progress percentage for the scaling workspace
	ScalingProgress *float64 `json:"scalingProgress,omitempty"`
	// Size of the workspace (in workspace size notation), such as "S-00" or "S-1"
	//
	Size string `json:"size"`
	// State of the workspace
	State State `json:"state"`
	// (If included in the output) The timestamp of when the workspace was terminated
	TerminatedAt *string `json:"terminatedAt,omitempty"`
	// ID of the workspace group containing the workspace
	WorkspaceGroupID string `json:"workspaceGroupID"`
	// ID of the workspace
	WorkspaceID string `json:"workspaceID"`
}

func (o *Workspace) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *Workspace) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *Workspace) GetLastResumedAt() *string {
	if o == nil {
		return nil
	}
	return o.LastResumedAt
}

func (o *Workspace) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Workspace) GetResumeAttachments() []ResumeAttachments {
	if o == nil {
		return nil
	}
	return o.ResumeAttachments
}

func (o *Workspace) GetScalingProgress() *float64 {
	if o == nil {
		return nil
	}
	return o.ScalingProgress
}

func (o *Workspace) GetSize() string {
	if o == nil {
		return ""
	}
	return o.Size
}

func (o *Workspace) GetState() State {
	if o == nil {
		return State("")
	}
	return o.State
}

func (o *Workspace) GetTerminatedAt() *string {
	if o == nil {
		return nil
	}
	return o.TerminatedAt
}

func (o *Workspace) GetWorkspaceGroupID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceGroupID
}

func (o *Workspace) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
